#!/usr/bin/env bash

mkdir -p pgn/twic
cd pgn/twic || exit 1

twic_min=$1
twic_max=$2

[[ -z $twic_max && -n $twic_min ]] && twic_max=$twic_min
[[ -z $twic_min ]] && twic_min=920
[[ -z $twic_max ]] && twic_max=9999

# download all pgn files
for file in $(seq $twic_min $twic_max)
do
    echo "downloading twic${file}g.zip"
    wget -q "https://theweekinchess.com/zips/twic${file}g.zip" || break
done

# unzip pgn
for file in *.zip
do
    [[ -e "$file" ]] || break
    unzip -o "$file"
    rm "$file"
done

# concatenate all pgn files
[[ -f twic.pgn ]] && rm twic.pgn
for file in *.pgn
do
    [[ -e "$file" ]] || break
    cat "${file}" >> twic.pgn
    echo "" >> twic.pgn
done
