---
search:
  file:
    arg: true
    desc: '[mandatory] PGN file (ex: "pgn/twic1368.pgn")'
    type: string
    short: f
    mandatory: true
  help:
    arg: false
    desc: Print usage
    short: h
  player:
    arg: true
    desc: Player name (white or black)
    type: string
    short: p
    mandatory: false
  white:
    arg: true
    desc: White player name
    type: string
    short: w
    mandatory: false
  black:
    arg: true
    desc: Black player name
    type: string
    short: b
    mandatory: false
  team:
    arg: true
    desc: Team name (white or black)
    type: string
    short: t
    mandatory: false
  fide_id:
    arg: true
    desc: FIDE Id (white or black)
    type: string
    short: F
    mandatory: false
  result:
    arg: true
    desc: Game result
    args:
      - "1-0"
      - "0-1"
      - "1/2-1/2"
    type: str
    short: r
  eco:
    arg: true
    desc: ECO opening name
    type: string
    short: e
    mandatory: false
  opening:
    arg: true
    desc: Opening name
    type: string
    short: o
    mandatory: false
  variation:
    arg: true
    desc: Opening variation name
    type: string
    short: V
    mandatory: false
  event:
    arg: true
    desc: Event name
    type: string
    short: E
    mandatory: false
  site:
    arg: true
    desc: Site (location)
    type: string
    short: s
    mandatory: false
  game_date:
    arg: true
    desc: 'Date of game (format: "YYYY.MM.DD")'
    type: date
    short: d
  event_date:
    arg: true
    desc: 'Date of event (format: "YYYY.MM.DD")'
    type: date
    short: D
  date_min:
    arg: true
    desc: 'Minimum date (format: "YYYY.MM.DD")'
    type: date
    mandatory: false
  date_max:
    arg: true
    desc: 'Maximum date (format: "YYYY.MM.DD")'
    type: date
    mandatory: false
  elo_min:
    arg: true
    desc: Minimum elo rating
    type: int
    mandatory: false
  elo_max:
    arg: true
    desc: Maximum elo rating
    type: int
    mandatory: false
  white_team:
    arg: true
    desc: White team name
    type: string
    mandatory: false
  black_team:
    arg: true
    desc: Black team name
    type: string
    mandatory: false
  white_fide_id:
    arg: true
    desc: White FIDE Id
    type: string
    mandatory: false
  black_fide_id:
    arg: true
    desc: Black FIDE Id
    type: string
    mandatory: false

